### ISSUE TITLE
[FeatureRequest] non-pool related sensor types

### ISSUE THREAD

**Issue by vobele** [wilsto/pool-monitor-card#22]
To open your card for a much larger group of user, you may add non-pool related sensor types like:

Air temp: °C (well, not really. This already works with advanced options temperature_setpoint and temperature_step) :white_check_mark:
Humidity: % (would just require an additional sensor type to choose) :bulb:
CO2: ppm (would just require an additional sensor type to choose) :bulb:
Radon: Bq/m³ (would just require an additional sensor type to choose) :bulb:
..

Bonus: may be adding the possibility to use more sensors of the same type in a row like:
Temp1, Temp2, Temp3, Temp4 ... Temp9
Humidity1, Humidity2, Humidity3 ... Humidity9
.. 

That would be so freakn awesome!
Regards

**Comment by gregtakacs** [comment]
So looking at the code the problem is that
1) these sensor rows are not dynamic, ie. they're all hard coded and
2) the corresponding custom icons are all png files residing off-site and not even part of the package (not ideal)

To enable custom types the code would have to reconsider how it's handling the different sensors, rather than hardcoding every type it should templateize. This is likely would be a significant refactor of the code.

**Comment by vobele** [comment]
Ok got it. However thank you for your feedback. Shall I close the request or let it open?

**Comment by gregtakacs** [comment]
Note that there is a sensor monitor card that allows you to use any arbitrary sensor: https://github.com/wilsto/sensor-monitor-card

**Comment by vobele** [comment]
Uuh.. totally missed that one! Awesome, thanks!
